# Generated by Django 4.2.7 on 2023-11-17 10:24

import CollectionCatalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectionCatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[CollectionCatalog.models.validate_image_extension]),
        ),
    ]
