# Generated by Django 4.2.7 on 2023-11-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectionCatalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='editeur',
            field=models.CharField(blank=True, help_text="veuillez saisir le nom de l'éditeur", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, choices=[('PO', 'Poche 11 cm x 18 cm'), ('DG', 'Digest 14 cm x 21.6 cm'), ('RO', 'Roman 15 cm x 21 cm'), ('RY', 'Royal 16 cm x 24 cm'), ('A4', 'A4 21 cm x 29,7 cm'), ('AU', 'Autre')], help_text="veuillez selectionner le type d'édition dans la liste déroulante", max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('RM', 'Roman'), ('BG', 'Biographie'), ('AB', 'Autobiographie'), ('MG', 'Manga'), ('ES', 'Essai'), ('BD', 'Bande Dessinée'), ('CS', 'Comics'), ('BL', 'Beau Livre'), ('AU', 'Autre')], help_text='choose the type of book', max_length=2),
        ),
        migrations.AlterField(
            model_name='watch',
            name='type_of_mecanism',
            field=models.CharField(blank=True, choices=[('MM', 'Mécanique manuel'), ('MA', 'Mécanique automatique'), ('QZ', 'Quartz (pile)')], help_text='Enter the type of mecanism of your watch, e.g. automatic', max_length=2, null=True),
        ),
    ]
